### ISSUE TITLE
PI 5 support

### ISSUE THREAD

**Issue by gilliangoud** [dgatwood/ndi_camera_control#9]
Hi!
First, thank you so much for your time and effort for making this.

The Pi5 seems to, due to hardware architecture, no longer support the pigpio library.
I have yet to delve into your code to see how much effort replacing this pibrary could be.

Have you thought about this yet or looked into it?

**Comment by dgatwood** [comment]
I'm one step ahead of you.  The code actually supports two different GPIO libraries, switchable with a #define — MRAA and pigpio.  I added the MRAA support a while back, because I couldn't get a Raspberry Pi 4, and had to substitute a Rock Pi.  Chances are, enabling the USE_MRAA flag will make it "just work" (ignoring any GPIO pin number changes that you might need to make).

**Comment by gilliangoud** [comment]
Brilliant!

After some struggles to build MRAA, I can confirm it does work on the Pi 5.
It still struggles to decode 1080p NDI|HX3, but works on both h264 and h265 encoding with the fast preset smoothly.
I've actually noticed that, wether it's MRAA or the Pi5, the PTZ feels a lot more smooth.

To get it to work I had move the "#endif" on line 2631 of cameracontroller.cpp below the led init block to line 2651, as that code was not happy without pigpio. Haven't looked into adding leds to my janky test setup anyhow :).

To replicate:
- Started from a dicaffeine raspbian base, [https://dicaffeine.com/raspbian](https://dicaffeine.com/raspbian)
- Followed Pi configuration from this repo for the /boot/config.txt, except I left the overlay in and added an dditional overlay for the specific touchscreen display I'm using. [Relevant issue](https://github.com/goodtft/LCD-show/issues/360)
```dtoverlay=ads7846,cs=1,penirq=25,penirq_pull=2,speed=50000,keep_vref_on=0,swapxy=0,pmax=255,xohms=150,xmin=200,xmax=3900,ymin=200,ymax=3900```
- Installed Avahi tools etc according to this repo
- Disabled X11 through raspi-config
- created /etc/ld.so.conf.d/ndi.conf with:
```/usr/local/lib/
/usr/local/lib/ndi_hx/
```
- Installed MRAA by:
```sudo apt-get install git build-essential swig python-dev nodejs-dev cmake libjson-c-dev
git clone https://github.com/intel-iot-devkit/mraa
cd mraa
mkdir build
cd build
cmake ..
make
sudo make install
```
- ran 'sudo ldconfig'
- Cloned both repostories and symlinked the relevant ioe-c files.
- edited the Makefile to use MRAA and edit the LDFLAGS to point to /usr/local/lib/

Thanks for your quick reaction, this got me so excited.

**Comment by dgatwood** [comment]
Feel free to send a patch for the #endif if that's causing a build failure.  If it is just hanging, that might be a pin number problem or something, in which case that's going to end up probably requiring a third set of pin numbers (unless they happen to match the Rock Pi pins).  Either way, feel free to send a patch when you get something working.
